# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea8c4ffddf08210b83bf7977e1f21ec61ba1f4d955af03b007396ee03e428823190b5c7700f3cf14186e73540a826b8050a60f2d74bc772865e7c90b675829d5

test:
  secret_key_base: 17cd5271b38ad95acbc7e72a41f22e7b0412a7aa6515ed76e729df2bb29ae312e7783741d9c4ac7485d605af7bc2742497955ed396406bb60533e308544aadf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
